// GENERATED by tools/gen_maps.py — do not edit by hand
const MAPS_GEN = {
 "world": {
  "name": "ルミナの大地",
  "tileset": "field",
  "tiles": [
   "########################################",
   "#...........T.T..........#.mmmmmmmmm.#.#",
   "#.........TTTTTTT..........mFFFFFFFm...#",
   "#.........TTTT.T.........#.mFFFFFFFm.#.#",
   "#......TT..T.TTTT..........mmmGmmmmm...#",
   "#.....TTTTTTTTT....T.~~.......pT;TT.#..#",
   "#....#TT.T#TTT.......~~.......pTT.T..T.#",
   "#....T....TTTTT.......~~..T...p.TTTT..T#",
   "#...TT.nn.TT.TT...T...~~......p.TTTTT.T#",
   "#...TT..p.TTTTT.......~~......p.T..TTTT#",
   "#....#TTp.#TTT.........~~.....pTTTT.TT.#",
   "#.....T.pTTTT..T.......~~.....pT.T.TTT.#",
   "#......TpTTT,,...pppppp==pppppp..TTT...#",
   "#....,,,pppppppppp.....~~;;;.;.;;......#",
   "#...,.,,..,,sssssps...~~;;;.;..;;;;.T..#",
   "#...T,T,,,,,sssssps....~~;;.;;;..;;....#",
   "#..T,TTT,,.,sssssps....~~;;;;;;.;;;....#",
   "#.T.TTTT,.,.,,sssp......~~.;;;;;;;.....#",
   "#.TT..TTT,.,.,...p......~~T;;;;;.;..;..#",
   "#.TTTTT.T........p.............~~~~~...#",
   "#..,.TT,,,.T.....p.f..........~~~~~~~..#",
   "#...,TT,,,.....f.p...........~~~~~~~~~.#",
   "#..,,ppppp.......p..........~~~~~~~~~~~#",
   "#..xppppVppp.....p..........~~~~~~~~~~~#",
   "#..xpRRRpRRRp....p..f....sss~~~~~~~~~~~#",
   "#.pxpHHHpHHHx....p.....sssss~~~~~~~~~~~#",
   "#.pxppppDpppx....p.....sssss~~~~~~~~~~~#",
   "#..ppppppppppppppp.....ssssss~~~~~~~~~~#",
   "#.....pppp...............sss..~~~~~~~~~#",
   "########################################"
  ],
  "encRate": 0.085,
  "zone": null,
  "warps": [
   {
    "x": 8,
    "y": 26,
    "to": "town",
    "tx": 12,
    "ty": 15,
    "dir": "down"
   },
   {
    "x": 7,
    "y": 8,
    "to": "cave",
    "tx": 9,
    "ty": 13,
    "dir": "up"
   },
   {
    "x": 8,
    "y": 8,
    "to": "cave",
    "tx": 10,
    "ty": 13,
    "dir": "up"
   },
   {
    "x": 30,
    "y": 4,
    "to": "castle",
    "tx": 14,
    "ty": 19,
    "dir": "up",
    "gate": "castleGate"
   }
  ],
  "chests": [
   {
    "x": 14,
    "y": 15,
    "id": "w_c1",
    "gold": 120
   },
   {
    "x": 16,
    "y": 16,
    "id": "w_c2",
    "item": "hipotion"
   },
   {
    "x": 15,
    "y": 17,
    "id": "w_c3",
    "item": "ether"
   },
   {
    "x": 26,
    "y": 26,
    "id": "w_c4",
    "gold": 200
   }
  ],
  "npcs": [],
  "triggers": []
 },
 "town": {
  "name": "ルミナの村",
  "tileset": "town",
  "tiles": [
   "TTTTTTTTTTTTTTTTTTTTTTTT",
   "T......................T",
   "T.RRRRR..........RRRRR.T",
   "T.HHDHH..........HHDHH.T",
   "T...p..............p...T",
   "T...p......V.......p...T",
   "T...p.f.f.....f....p...T",
   "T...p...........f..p...T",
   "T...pppppppppppppppp...T",
   "T.xx........p.....f.xx.T",
   "T....f......p........x.T",
   "T...........p..RRRR....T",
   "T...........p..HHDH....T",
   "T...........pppppp.....T",
   "T.......f....p.....f...T",
   "T............p.........T",
   "T.........!!!!!!!......T",
   "TTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "encRate": 0.0,
  "zone": null,
  "warps": [
   {
    "x": 4,
    "y": 3,
    "to": "elder",
    "tx": 5,
    "ty": 6,
    "dir": "up"
   },
   {
    "x": 19,
    "y": 3,
    "to": "inn",
    "tx": 5,
    "ty": 6,
    "dir": "up"
   },
   {
    "x": 17,
    "y": 12,
    "to": "shop",
    "tx": 5,
    "ty": 6,
    "dir": "up"
   },
   {
    "x": 10,
    "y": 16,
    "to": "world",
    "tx": 8,
    "ty": 27,
    "dir": "down"
   },
   {
    "x": 11,
    "y": 16,
    "to": "world",
    "tx": 8,
    "ty": 27,
    "dir": "down"
   },
   {
    "x": 12,
    "y": 16,
    "to": "world",
    "tx": 8,
    "ty": 27,
    "dir": "down"
   },
   {
    "x": 13,
    "y": 16,
    "to": "world",
    "tx": 8,
    "ty": 27,
    "dir": "down"
   },
   {
    "x": 14,
    "y": 16,
    "to": "world",
    "tx": 8,
    "ty": 27,
    "dir": "down"
   },
   {
    "x": 15,
    "y": 16,
    "to": "world",
    "tx": 8,
    "ty": 27,
    "dir": "down"
   },
   {
    "x": 16,
    "y": 16,
    "to": "world",
    "tx": 8,
    "ty": 27,
    "dir": "down"
   }
  ],
  "chests": [],
  "npcs": [
   {
    "x": 13,
    "y": 14,
    "spr": "npc_guard",
    "name": "もりのへいし",
    "talk": "guard"
   },
   {
    "x": 7,
    "y": 7,
    "spr": "npc_vil1",
    "name": "むらびと",
    "talk": "vil1",
    "wander": true
   },
   {
    "x": 16,
    "y": 9,
    "spr": "npc_vil2",
    "name": "むらびと",
    "talk": "vil2",
    "wander": true
   },
   {
    "x": 13,
    "y": 6,
    "spr": "npc_vil2",
    "name": "おばあさん",
    "talk": "vil3"
   }
  ],
  "triggers": []
 },
 "inn": {
  "name": "宿屋",
  "tileset": "inside",
  "tiles": [
   "HHHHHHHHHHH",
   "HQQFFFFFFjH",
   "HFFFFFFFuFH",
   "HFFFFFFFFFH",
   "HFqqqqqqqFH",
   "HFFFrrrFFFH",
   "HFFFrrrFFFH",
   "HHHH!!!HHHH"
  ],
  "encRate": 0.0,
  "zone": null,
  "warps": [
   {
    "x": 4,
    "y": 7,
    "to": "town",
    "tx": 19,
    "ty": 4,
    "dir": "down"
   },
   {
    "x": 5,
    "y": 7,
    "to": "town",
    "tx": 19,
    "ty": 4,
    "dir": "down"
   },
   {
    "x": 6,
    "y": 7,
    "to": "town",
    "tx": 19,
    "ty": 4,
    "dir": "down"
   }
  ],
  "chests": [],
  "npcs": [
   {
    "x": 5,
    "y": 3,
    "spr": "npc_inn",
    "name": "やどやの しゅじん",
    "talk": "inn",
    "counter": [
     4,
     5
    ]
   }
  ],
  "triggers": []
 },
 "shop": {
  "name": "ぶきぐ屋",
  "tileset": "inside",
  "tiles": [
   "HHHHHHHHHHH",
   "HjFFFFFFFjH",
   "HuFFFFFFFuH",
   "HFFFFFFFFFH",
   "HFqqqqqqqFH",
   "HFFFrrrFFFH",
   "HFFFrrrFFFH",
   "HHHH!!!HHHH"
  ],
  "encRate": 0.0,
  "zone": null,
  "warps": [
   {
    "x": 4,
    "y": 7,
    "to": "town",
    "tx": 17,
    "ty": 13,
    "dir": "down"
   },
   {
    "x": 5,
    "y": 7,
    "to": "town",
    "tx": 17,
    "ty": 13,
    "dir": "down"
   },
   {
    "x": 6,
    "y": 7,
    "to": "town",
    "tx": 17,
    "ty": 13,
    "dir": "down"
   }
  ],
  "chests": [],
  "npcs": [
   {
    "x": 5,
    "y": 3,
    "spr": "npc_shop",
    "name": "てんしゅ",
    "talk": "shop",
    "counter": [
     4,
     5
    ]
   }
  ],
  "triggers": []
 },
 "elder": {
  "name": "ちょうろうの家",
  "tileset": "inside",
  "tiles": [
   "HHHHHHHHHHH",
   "HFFFFFFFFjH",
   "HFuFFFFFFQH",
   "HFFFFFFFFFH",
   "HFFFFFFFFFH",
   "HFFFrrrFuFH",
   "HFFFrrrFFFH",
   "HHHH!!!HHHH"
  ],
  "encRate": 0.0,
  "zone": null,
  "warps": [
   {
    "x": 4,
    "y": 7,
    "to": "town",
    "tx": 4,
    "ty": 4,
    "dir": "down"
   },
   {
    "x": 5,
    "y": 7,
    "to": "town",
    "tx": 4,
    "ty": 4,
    "dir": "down"
   },
   {
    "x": 6,
    "y": 7,
    "to": "town",
    "tx": 4,
    "ty": 4,
    "dir": "down"
   }
  ],
  "chests": [],
  "npcs": [
   {
    "x": 5,
    "y": 2,
    "spr": "npc_elder",
    "name": "ちょうろう",
    "talk": "elder"
   }
  ],
  "triggers": []
 },
 "cave": {
  "name": "北の洞窟",
  "tileset": "cave",
  "tiles": [
   "####################",
   "#ssssssssssssssssss#",
   "#sossssssosssssssos#",
   "#ssss#sssssssssssss#",
   "#ssss#s###s##ssssss#",
   "#ssss#sssssssssssss#",
   "#ssssssPFFFFPs#ssss#",
   "#ssss#ssFFFFss#ssss#",
   "#ssss#ssFFFFss#ssss#",
   "#ssss#sssssssssssss#",
   "#sssssssssssss#ssss#",
   "#sssssssssssss#ssss#",
   "#sosssssssssss#ssos#",
   "#ssssssssssssssssss#",
   "#ssssssss!!ssssssss#",
   "####################"
  ],
  "encRate": 0.11,
  "zone": "cave",
  "warps": [
   {
    "x": 9,
    "y": 14,
    "to": "world",
    "tx": 7,
    "ty": 9,
    "dir": "down"
   },
   {
    "x": 10,
    "y": 14,
    "to": "world",
    "tx": 7,
    "ty": 9,
    "dir": "down"
   }
  ],
  "chests": [
   {
    "x": 9,
    "y": 6,
    "id": "cv_c1",
    "key": "hikariKey"
   },
   {
    "x": 10,
    "y": 6,
    "id": "cv_c2",
    "gold": 250
   },
   {
    "x": 1,
    "y": 1,
    "id": "cv_c3",
    "item": "elixir"
   },
   {
    "x": 18,
    "y": 13,
    "id": "cv_c4",
    "item": "hipotion"
   }
  ],
  "npcs": [],
  "triggers": []
 },
 "castle": {
  "name": "魔王城 いっかい",
  "tileset": "castle",
  "tiles": [
   "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
   "WFFFFFFFFFFFFFFFFFFFFFFFFFFFFW",
   "WFFFFWFFFFFWFFFSFFFFFFFFFFFFFW",
   "WFFPFWFFFFFWFFFFFFFFFFFFFFPFFW",
   "WFFFFWFFFFFFFWWWFWWFFFFFFFFFFW",
   "WoFFFFFFFFFWFFFFFFWFFFFFFFFFoW",
   "WFFFFWFFFFFWFFFPFFWFFFFFFFFFFW",
   "WFFFFWFFFFFFFFFFFFFFFFFFFFFFFW",
   "WFFFFWFFFFFFFFFFFFWFFFFFFFFFFW",
   "WFFFFWWWWFWWFFFFFFWFFFFFFFFFFW",
   "WFFFFWFFFFFFFFFFFFWWWFWWWFFFFW",
   "WFFFFWFFFFFFFFFFFFFFFFFFFFFFFW",
   "WFFFFFFFFFFFFFFFFFFFFFFFWFFFFW",
   "WFFFFWFFFFFFFFFFFFFFFFFFWFFFFW",
   "WoFFFWFFFFFFFFFFFFFFFFFFWFFFoW",
   "WFFFFWFPFFFFFFFFFFFFFFFFFFFFFW",
   "WFFFFWFFFFFFFFFFFFFFFFFFWFFFFW",
   "WFFFFWFWWWFWWWFFFFFFWWFWWWFFFW",
   "WFFPFFFFFFFFFFFFFFFFFFFFWFFPFW",
   "WFFFFFFFFFFFFWFFFFFFFFFFFFFFFW",
   "WFFFFFFFoFFFF!!!!FFFoFFFFFFFFW",
   "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
  ],
  "encRate": 0.11,
  "zone": "castle",
  "warps": [
   {
    "x": 15,
    "y": 2,
    "to": "castle2",
    "tx": 10,
    "ty": 13,
    "dir": "up"
   },
   {
    "x": 13,
    "y": 20,
    "to": "world",
    "tx": 30,
    "ty": 5,
    "dir": "down"
   },
   {
    "x": 14,
    "y": 20,
    "to": "world",
    "tx": 30,
    "ty": 5,
    "dir": "down"
   },
   {
    "x": 15,
    "y": 20,
    "to": "world",
    "tx": 30,
    "ty": 5,
    "dir": "down"
   },
   {
    "x": 16,
    "y": 20,
    "to": "world",
    "tx": 30,
    "ty": 5,
    "dir": "down"
   }
  ],
  "chests": [
   {
    "x": 2,
    "y": 2,
    "id": "cs_c1",
    "gold": 500
   },
   {
    "x": 27,
    "y": 2,
    "id": "cs_c2",
    "item": "elixir"
   },
   {
    "x": 26,
    "y": 14,
    "id": "cs_c3",
    "gear": "w_light"
   },
   {
    "x": 3,
    "y": 20,
    "id": "cs_c4",
    "item": "ether"
   }
  ],
  "npcs": [],
  "triggers": []
 },
 "castle2": {
  "name": "魔王城 にかい",
  "tileset": "castle",
  "tiles": [
   "WWWWWWWWWWWWWWWWWWWWWW",
   "WFFFFFFFFFZFFFFFFFFFFW",
   "WFFFFFFoFFFFFoFWFFFFFW",
   "WFFPFWFFFFFFFFFWFFPFFW",
   "WoFFFWFFFWFFFFFWFFFFoW",
   "WFFFFWFFFWFFFFFFFFFFFW",
   "WFFFFWFFFWWFWWWWFFFFFW",
   "WFFFFFFFFWFFFFFWFFFFFW",
   "WFFFFWFFFWFFFFFWFFFFFW",
   "WFFFFWFFFWFFFFFWWFWWFW",
   "WFFFFWFFFFFFFFFFFWFFFW",
   "WoFFFWFFFWFFFFFFFWFFFW",
   "WFFPFFFFFWFFFFFFFWFFoW",
   "WFFFFFFFFWFFFFFFFWPFFW",
   "WFFFFFFFFFSFFFFFFFFFFW",
   "WWWWWWWWWWWWWWWWWWWWWW"
  ],
  "encRate": 0.12,
  "zone": "castle2",
  "warps": [
   {
    "x": 10,
    "y": 14,
    "to": "castle",
    "tx": 15,
    "ty": 3,
    "dir": "down"
   },
   {
    "x": 10,
    "y": 1,
    "to": "bossroom",
    "tx": 5,
    "ty": 7,
    "dir": "up"
   }
  ],
  "chests": [
   {
    "x": 19,
    "y": 2,
    "id": "c2_c1",
    "gear": "a_dragon"
   },
   {
    "x": 1,
    "y": 13,
    "id": "c2_c2",
    "item": "elixir"
   }
  ],
  "npcs": [],
  "triggers": []
 },
 "bossroom": {
  "name": "魔王の間",
  "tileset": "castle",
  "tiles": [
   "WWWWWWWWWWW",
   "WFFFFFFFFFW",
   "WFPFrrrFPFW",
   "WFFFrrrFFFW",
   "WFFFrrrFFFW",
   "WFFFrrrFFFW",
   "WFPFrrrFPFW",
   "WFFFFFFFFFW",
   "WWWW!!!WWWW"
  ],
  "encRate": 0.0,
  "zone": null,
  "warps": [
   {
    "x": 4,
    "y": 8,
    "to": "castle2",
    "tx": 10,
    "ty": 2,
    "dir": "down"
   },
   {
    "x": 5,
    "y": 8,
    "to": "castle2",
    "tx": 10,
    "ty": 2,
    "dir": "down"
   },
   {
    "x": 6,
    "y": 8,
    "to": "castle2",
    "tx": 10,
    "ty": 2,
    "dir": "down"
   }
  ],
  "chests": [],
  "npcs": [
   {
    "x": 5,
    "y": 2,
    "spr": "en_boss",
    "name": "魔王ヴァルドラス",
    "talk": "boss",
    "big": true
   }
  ],
  "triggers": [
   {
    "x": 5,
    "y": 5,
    "script": "bossApproach"
   }
  ]
 }
};
